/* Assessment page copy is separate so the form can evolve without a site-wide rewrite.
   Arabic is written for Arabic-speaking visitors, not as a literal English translation. */
Object.assign(window.FaseehTranslations, {
  'booking.pageTitle': ['Book Your Free Assessment | Faseeh Academy', 'احجز موعدًا مجانيًا لتحديد مستواك | أكاديمية فصيح'],
  'booking.description': ['Arrange your free Quran and Tajweed assessment with Faseeh Academy. Send a short enquiry or speak with us on Messenger.', 'ابدأ تعلّم القرآن والتجويد مع أكاديمية فصيح. أرسل طلبك لحجز تحديد مستوى وحصة تجريبية مجانًا، أو تواصل معنا عبر ماسنجر.'],
  'booking.offer': ['FREE Assessment & Trial Session', 'تحديد مستوى وحصة تجريبية مجانًا'],
  'booking.heroTitle': ['Your next step,', 'ابدأ معنا،'],
  'booking.heroEm': ['made simple.', 'بخطوة بسيطة.'],
  'booking.heroIntro': ['Tell us a little about your learning goals. We’ll help you find the right teacher and a time that works for you.', 'أخبرنا بما ترغب في تعلّمه، وسنساعدك في اختيار المعلّم المناسب وترتيب موعد يلائمك.'],
  'booking.noCommitment': ['Free to try. No commitment.', 'جرّب مجانًا، ثم قرّر ما يناسبك.'],
  'booking.optionsLabel': ['Choose how to get in touch', 'اختر الطريقة الأنسب للتواصل معنا'],
  'booking.recommended': ['Recommended', 'ننصحك بهذا الخيار'],
  'booking.formOption': ['Let us arrange it for you', 'دعنا نرتّب حصتك الأولى'],
  'booking.formOptionIntro': ['Fill in a short form, and our team will email you shortly to arrange your free assessment.', 'املأ النموذج المختصر، وسنتواصل معك قريبًا عبر البريد الإلكتروني لترتيب موعد تحديد المستوى المجاني.'],
  'booking.formOptionCta': ['Fill in the short form', 'املأ نموذج الحجز'],
  'booking.chatKicker': ['Prefer a conversation?', 'تفضّل التحدث معنا أولًا؟'],
  'booking.chatOption': ['Message us directly', 'راسلنا مباشرة'],
  'booking.chatOptionIntro': ['Ask a question or discuss your options with our team on Messenger.', 'يسعدنا الرد على أسئلتك ومساعدتك في اختيار ما يناسبك عبر ماسنجر.'],
  'booking.chatCta': ['Chat on Messenger', 'تواصل عبر ماسنجر'],
  'booking.formEyebrow': ['A beginning that fits you', 'بداية تناسبك'],
  'booking.formTitle': ['Let’s plan your first lesson.', 'لنرتّب حصتك الأولى.'],
  'booking.formIntro': ['A few details help us understand what you need. We’ll take care of the next steps together.', 'هذه المعلومات البسيطة تساعدنا في معرفة احتياجاتك، لنختار معًا البداية المناسبة لك.'],
  'booking.step1': ['Tell us about the learner', 'عرّفنا باحتياجات الطالب'],
  'booking.step1Intro': ['Your goals, starting point and availability.', 'ما الذي يرغب في تعلّمه؟ وما المواعيد المناسبة له؟'],
  'booking.step2': ['Look out for our email', 'انتظر رسالتنا على بريدك'],
  'booking.step2Intro': ['We’ll contact you to agree on a suitable time.', 'سنتواصل معك للاتفاق على موعد مناسب.'],
  'booking.step3': ['Meet your teacher', 'تعرّف إلى معلّمك'],
  'booking.step3Intro': ['Try a lesson and discuss a plan that suits you.', 'جرّب الحصة وناقش مع معلّمك خطة التعلّم المناسبة.'],
  'booking.guideNote': ['No payment details needed. Choose whether to continue after your trial.', 'لا نطلب أي بيانات للدفع. بعد الحصة التجريبية، لك حرية اختيار الاستمرار.'],
  'booking.detailsTitle': ['Your assessment request', 'طلب حجز تحديد المستوى'],
  'booking.fieldsNote': ['Fields marked * are required.', 'الحقول التي تحمل علامة * مطلوبة.'],
  'booking.name': ['Your name', 'الاسم'],
  'booking.guardian': ['For a student under 18, a parent or guardian should complete this form using their own contact details.', 'إذا كان الطالب دون 18 عامًا، يُرجى أن يملأ وليّ الأمر النموذج باسمه وبيانات التواصل الخاصة به.'],
  'booking.email': ['Your email address', 'البريد الإلكتروني'],
  'booking.emailHelp': ['We’ll reply to this email to arrange your assessment.', 'سنتواصل معك على هذا البريد لترتيب موعد تحديد المستوى.'],
  'booking.age': ['Student’s age', 'عمر الطالب'],
  'booking.ageChoose': ['Choose an age group', 'اختر الفئة العمرية'],
  'booking.ageUnder7': ['Under 7', 'أقل من 7 سنوات'],
  'booking.age7to12': ['7–12 years', 'من 7 إلى 12 سنة'],
  'booking.age13to17': ['13–17 years', 'من 13 إلى 17 سنة'],
  'booking.ageAdult': ['18 or older', '18 سنة فأكثر'],
  'booking.program': ['Interested program', 'البرنامج المطلوب'],
  'booking.programUnsure': ['Help me choose', 'أحتاج إلى المساعدة في الاختيار'],
  'booking.programMemorization': ['Quran Memorization', 'حفظ القرآن الكريم'],
  'booking.programBeginner': ['Tajweed for Beginners', 'التجويد للمبتدئين'],
  'booking.programIntermediate': ['Tajweed for Intermediate', 'التجويد للمستوى المتوسط'],
  'booking.programMakharij': ['Makharij Course', 'دورة مخارج الحروف'],
  'booking.programQiraiyya': ['Qira’iyya Course', 'دورة القرائية'],
  'booking.programArabic': ['Arabic Reading & Writing', 'القراءة والكتابة بالعربية'],
  'booking.country': ['Country of residence', 'بلد الإقامة'],
  'booking.schedule': ['Preferred lesson times', 'المواعيد المناسبة للدراسة'],
  'booking.optional': ['(optional)', '(اختياري)'],
  'booking.schedulePlaceholder': ['e.g. Weekday evenings, Dubai time', 'مثلًا: مساءً خلال الأسبوع، بتوقيت دبي'],
  'booking.moreDetails': ['Add learning preferences', 'أضف تفاصيل عن احتياجاتك'],
  'booking.level': ['Current level', 'المستوى الحالي'],
  'booking.levelUnsure': ['Not sure', 'لست متأكدًا من مستواي'],
  'booking.levelNew': ['Complete beginner', 'مبتدئ من الصفر'],
  'booking.levelSome': ['Some reading experience', 'لدي معرفة بأساسيات القراءة'],
  'booking.levelConfident': ['Reading confidently; developing recitation', 'أقرأ جيدًا وأرغب في تحسين تلاوتي'],
  'booking.plan': ['Preferred tier', 'الباقة المطلوبة'],
  'booking.planUnsure': ['Not decided yet', 'لم أحدد بعد'],
  'booking.planHalaqah': ['Halaqah — $7/hour', 'الحلقة — 7 دولارات للساعة'],
  'booking.planPrivate': ['Private — $10/hour', 'الفردية — 10 دولارات للساعة'],
  'booking.planExcellence': ['Excellence — $15/hour', 'التميّز — 15 دولارًا للساعة'],
  'booking.message': ['Anything you’d like us to know?', 'هل تود إضافة شيء؟'],
  'booking.messagePlaceholder': ['Learning goals, teacher preferences or a question…', 'هدفك من الدراسة، أو تفضيلك لمعلّم أو معلّمة، أو أي استفسار…'],
  'booking.messageHelp': ['Please don’t include sensitive personal details.', 'يُرجى عدم ذكر أي معلومات شخصية حساسة.'],
  'booking.consent': ['I agree to receive emails from Faseeh Academy about this enquiry.', 'أوافق على تواصل أكاديمية فصيح معي عبر البريد الإلكتروني بشأن هذا الطلب.'],
  'booking.privacyBefore': ['Your details are sent through ', 'تُرسل بياناتك عبر خدمة '],
  'booking.privacyAfter': [' and used to respond to your enquiry.', ' وتُستخدم للرد على طلبك.'],
  'booking.submit': ['Request my free assessment', 'أرسل طلب الحجز المجاني'],
  'booking.submitNote': ['We’ll email you shortly. Your lesson time will be confirmed together.', 'سنتواصل معك قريبًا عبر البريد الإلكتروني للاتفاق على موعد الحصة.'],
  'booking.sending': ['Sending your request…', 'جارٍ إرسال طلبك…'],
  'booking.required': ['Please complete this field.', 'يُرجى إكمال هذا الحقل.'],
  'booking.emailInvalid': ['Please enter a valid email address.', 'يُرجى كتابة بريد إلكتروني صحيح.'],
  'booking.consentRequired': ['Please agree to email contact so we can respond to your request.', 'يُرجى الموافقة على التواصل عبر البريد الإلكتروني حتى نتمكن من الرد على طلبك.'],
  'booking.error': ['We couldn’t confirm your request. Your details are still here. Please try again, or contact us on Messenger.', 'لم نتمكن من تأكيد إرسال طلبك. بياناتك ما زالت في النموذج؛ يُرجى المحاولة مرة أخرى أو التواصل معنا عبر ماسنجر.'],
  'booking.timeout': ['The response is taking longer than expected. Your request may have been received. You can contact us on Messenger to check, or try again.', 'تأخر الرد من خدمة الإرسال، وقد يكون طلبك قد وصل بالفعل. يمكنك التواصل معنا عبر ماسنجر للتأكد، أو المحاولة مرة أخرى.'],
  'booking.unconfirmed': ['The form service hasn’t confirmed your request. Please contact us on Messenger, or try again later. Your details are still here.', 'لم تؤكد خدمة النماذج إرسال طلبك. يُرجى التواصل معنا عبر ماسنجر أو المحاولة لاحقًا. بياناتك ما زالت في النموذج.'],
  'booking.localPreview': ['Please open this form through the website to submit it. Local file previews cannot send requests.', 'لإرسال الطلب، يُرجى فتح النموذج من الموقع. لا يمكن إرسال الطلبات من نسخة محفوظة على الجهاز.'],
  'booking.successEyebrow': ['Your next step is underway', 'شكرًا لتواصلك معنا'],
  'booking.successTitle': ['Request submitted.', 'تم إرسال طلبك.'],
  'booking.successIntro': ['We’ll email you shortly to arrange your free assessment. This does not confirm a lesson time.', 'سنتواصل معك قريبًا عبر البريد الإلكتروني لترتيب موعد تحديد المستوى المجاني. لم يُحدد موعد الحصة بعد؛ سنؤكده معك عند التواصل.'],
  'booking.reference': ['Request reference', 'رقم الطلب'],
  'booking.backHome': ['Back to the homepage', 'العودة إلى الصفحة الرئيسية'],
  'booking.fallback': ['Prefer to talk instead?', 'تفضّل التواصل المباشر؟']
});
